language: java

jdk:
  - oraclejdk7

script: ./gradlew build

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-south-1"  
  app: "SpringBoot"
  env: "springboot-env"
  bucket_name: "aws.ravikp.springboot"
  zip_file: "./build/fulljar/springboot.jar"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
