language: java

jdk:
  - oraclejdk7

script: ./gradlew build

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  app: SpringBoot
  env: springboot-env
  zip_file: 'build/fulljar/springboot.jar'
  bucket_name: aws.ravikp.springboot
  region: ap-south-1  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY    

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
