language: java

jdk:
  - oraclejdk7

install:
  - pip install awscli

script: 
  - aws --version
  - ./gradlew build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: aws.ravikp.springboot
    region: ap-south-1
    local_dir: ./build/fulljar
    skip_cleanup: true
    upload-dir: full-jar-builds
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: aws.ravikp.springboot
    region: ap-south-1
    local_dir: ./build/distributions
    skip_cleanup: true
    upload-dir: distributions  
  # - provider: elasticbeanstalk
  #   access_key_id: $AWS_ACCESS_KEY
  #   secret_access_key: $AWS_SECRET_KEY
  #   app: SpringBoot
  #   env: springboot-env
  #   skip_cleanup: true
  #   zip_file: ./build/distributions/springboot.zip  
  #   bucket_name: aws.ravikp.springboot
  #   bucket_path: elasticbeanstalk-builds
  #   region: ap-south-1
  #   only_create_app_version: true
    
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
