language: java

jdk:
  - oraclejdk7

script: ./gradlew build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: aws.ravikp.springboot
    region: ap-south-1
    local_dir: ./build/fulljar
    skip_cleanup: true
    upload-dir: full-jar-builds
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: aws.ravikp.springboot
    region: ap-south-1
    local_dir: ./build/distributions
    skip_cleanup: true
    upload-dir: distributions  
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
